version: '3'
services:
  client:
      build: 
       context: .
       dockerfile: ./client.Dockerfile
      ports:
      - "8081:8081"
      environment:
       - SERVER_HOST=server
        
      networks:
      - wow-network
     
  server:
      build: 
       context: .
       dockerfile: ./server.Dockerfile
      ports:
      - "8080:8080"
      environment:
       - SERVER_HOST=server
      hostname: server

      networks:
      - wow-network
     
networks:
  wow-network:
    driver: bridge